apiVersion: apps/v1
kind: Deployment
metadata:
  name: task1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task1
  template:
    metadata:
      labels:
        app: task1
    spec:
      containers:
      - name: task1
        image: zeebe-java
        imagePullPolicy: Always
        args: ['#REPLACEME']
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                - broker
            topologyKey: kubernetes.io/hostname