apiVersion: v1
kind: Service
metadata:
  annotations:
    environment.tess.io/name: dev
  labels:
    app.kubernetes.io/component: gateway
    app.kubernetes.io/instance: lnp
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zeebe-cluster-helm
    environment.tess.io/name: dev
  name: lnp-zeebe-gtwy-svc
  namespace: mkodnani-ns
spec:
  clusterIP: None
  ports:
  - name: http
    port: 9600
    protocol: TCP
    targetPort: 9600
  - name: gateway
    port: 26500
    protocol: TCP
    targetPort: 26500
  selector:
    app.kubernetes.io/component: gateway
    app.kubernetes.io/instance: lnp
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zeebe-cluster-helm
  sessionAffinity: None
  type: ClusterIP
